config/routes.rb
Rails.application.routes.draw do

  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'sign_up' => 'users#new', :as => 'sign_up'
  
  root :to => 'conversations#index', :as => 'home'
  
  resources :users
  resources :sessions
  resources :conversations do
    resources :messages
    resource :user_conversations
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
 	has_many :user_conversations
 	has_many :users, through: :user_conversations
	has_many :messages, dependent: :destroy
	
	#scope :between, -> (sender_id, recipient_id) do
 	#	where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 	#end

 	def self.for_patient(patient)
 		UserConversation.where(user_id: patient.id).map{ |uc| uc.conversation }.first
 	end

end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :conversation
 	belongs_to :user
 	validates_presence_of :body, :conversation_id, :user_id

 	scope :unread, -> { where(read: false) }

 	def message_time
  	created_at.strftime("%m/%d/%y at %l:%M %p")
 	end
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	has_many :user_conversations
	has_many :chatrooms, through: :user_conversations
	has_many :messages

	validates_confirmation_of :password, :on => :create, :message => "Passwords do not match"
	validates_presence_of :password, :on => :create, :message => "can't be blank"
	validates_presence_of :email, :on => :create, :message => "can't be blank"
	validates_presence_of :first_name, :last_name, :role
	validates_uniqueness_of :email, :on => :create
	validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+[a-z]{2,})\z/i, message: "is not a valid format"
	validates_inclusion_of :role, in: %w( patient care_manager )

	scope :alphabetical, -> { order('first_name, last_name') }

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def full_name
    first_name + " " + last_name
  end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/models/user_conversation.rb
class UserConversation < ActiveRecord::Base
	belongs_to :conversation
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :authenticate_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authenticate_user
    if !current_user
      redirect_to log_in_path, notice: "Please sign in to access the messaging system."
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
 	before_action :authenticate_user
	
	def index
 		@conversations = Conversation.all
 		@patients = User.where(role: "patient").alphabetical
 		if current_user.role == "patient"
 			@patient_conversation = Conversation.for_patient(current_user)
 		end
 	end

	def create
 		if Conversation.for_patient(params[:patient_id]).present?
    	@conversation = Conversation.for_patient(params[:patient_id]).first
 		else
  		@conversation = Conversation.create!(conversation_params)
 		end

 		redirect_to conversation_messages_path(@conversation)
	end

	private
 	
 	def conversation_params
  	params.require(:conversation)
 	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    if @messages.unread.count > 0
      if current_user.role == "patient"
        @messages.unread.each do |message|
          if message.user_id != current_user.id
            message.read = true
            message.save
          end
        end
      else # care manager
        @messages.unread.each do |message|
          if message.user_id != current_user.id
            if message.user.role == "patient"
              message.read = true
              message.save
            end
          end
        end
      end  
      #@messages.unread.each do |message|
      #  if message.user_id != current_user.id
      #    message.read = true
      #    message.save
      #  end
      #end
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end
  
  def create
    @message = @conversation.messages.new(message_params)
    @message.user = current_user
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private
  
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to home_path, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to log_in_path, :notice => "Logged out!"
	end
end

app/controllers/user_conversations_controller.rb
class UserConversationsController < ApplicationController
  before_action :authenticate_user
  before_action :set_conversation

  def create
    @user_conversation = @conversation.user_conversations.where(user_id: current_user.id).first_or_create
    redirect_to conversation_messages_path(@conversation)
  end

  private
    def set_conversation
      @conversation = Conversation.find(params[:conversation_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	  	session[:user_id] = @user.id
      if @user.role == "patient"
        conversation = Conversation.create!
        UserConversation.create(user_id: @user.id, conversation_id: conversation.id)
      end
	    redirect_to home_path, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end

	private

	def user_params
    params.require(:user).permit(:first_name, :last_name, :role, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/create.html.erb
<h1>Conversations#create</h1>
<p>Find me in app/views/conversations/create.html.erb</p>

app/views/conversations/index.html.erb
<% if current_user.role == "care_manager" %>
	<h1>Care Manager Dashboard</h1>
<% else %>
	<h1>Your Messages</h1>
<% end %>

<% if current_user.role == "patient" %>
	<h2>Inbox</h2>
	<% if @patient_conversation.present? %>
		<div class="panel panel-default">
			<div class="panel-body">
				<%= link_to "Your Care Conversation", conversation_messages_path(@patient_conversation)%>
				<% if @patient_conversation.messages.present? %>
					<% if @patient_conversation.messages.last.user_id != current_user.id %>
						<% if @patient_conversation.messages.unread.count > 0 %>
							<strong>(<%= @patient_conversation.messages.unread.count %> unread)</strong>
						<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

<% if current_user.role == "care_manager" %>
	<h2>All Patients</h2>
	<% @patients.each do |patient| %>
		<% conversation = Conversation.for_patient(patient) %>
		<div class="panel panel-default">
			<div class="panel-body">
				<%= link_to patient.full_name, conversation_messages_path(conversation) %>
				<% if conversation.messages.present? %>
					<% if conversation.messages.last.user_id != current_user.id %>
						<% if conversation.messages.last.user.role == "patient" %>
							<% if conversation.messages.unread.count > 0 %>
								<strong>(<%= conversation.messages.unread.count %> unread)</strong>
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/conversations/new.html.erb
<h1>Conversations#new</h1>
<p>Find me in app/views/conversations/new.html.erb</p>

app/views/conversations/show.html.erb
<h1>Conversations#show</h1>
<p>Find me in app/views/conversations/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <div class="navbar-brand">
	      	<%= link_to "MessageApp", home_path %>
	      </div>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse">
	      <ul class="nav navbar-nav navbar-right">
	        <% if current_user %>
				    <li><%= link_to current_user.first_name, home_path %></li>
				    <li><%= link_to "Log out", log_out_path %></li>
				  <% else %>
				    <li><%= link_to "Sign Up", sign_up_path %></li>
				    <li><%= link_to "Log In", log_in_path %></li>
				  <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div>
	</nav>
	<div class="container">
		<div class="row">
	    <div class="col-xs-12">
	      <% flash.each do |name, msg| %>
				  <%= content_tag :div, msg, :id => "flash_#{name}" %>
				<% end %>
	      <%= yield %>
	    </div>
	  </div>
  </div>

</body>
</html>

app/views/messages/index.html.erb
<% if @over_ten %>
  <%= link_to 'Show Previous', '?m=all' %>
<% end %>

<% @messages.each do |message| %>
  <% if message.body %>
    <% user = User.find(message.user_id) %>
    <div class="text-muted"><%= user.first_name %></div>
    <div class="panel panel-default"> 
      <div class="panel-body"> 
        <%= message.body %>
        <small class="pull-right text-muted"><i class="fa fa-clock-o"></i> <%= message.message_time %></small>
      </div>
    </div>
  <% end %>
<% end %>

<%= form_for [@conversation, @message] do |f| %>
  <div class="input-group">
    <%= f.text_area :body, class: "form-control", placeholder: "Type a message...", autofocus: true %>
    <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
    <span class="input-group-btn">
      <%= f.submit "Send", class: "btn btn-primary btn-lg send-button" %>
    </span>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="row">
	<div class="col-md-4 offset-md-4">
		<%= form_for @user do |f| %>
		  <% if @user.errors.any? %>
		    <div class="error_messages">
		      <h2>Form is invalid</h2>
		      <ul>
		        <% for message in @user.errors.full_messages %>
		          <li><%= message %></li>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>
		  <div class="form-group">
		    <%= f.label :first_name %><br />
		    <%= f.text_field :first_name, class: "form-control" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :last_name %><br />
		    <%= f.text_field :last_name, class: "form-control" %>
		  </div>
		  <div class="form-group">
		    Are you a Patient or a Care Manager?<br />
		    <%= f.radio_button :role, 'patient', :checked => true %> Patient
		  	<%= f.radio_button :role, 'care_manager' %> Care Manager
		  </div>
		  <div class="form-group">
		    <%= f.label :email %><br />
		    <%= f.text_field :email, class: "form-control" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :password %><br />
		    <%= f.password_field :password, class: "form-control" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :password_confirmation %><br />
		    <%= f.password_field :password_confirmation, class: "form-control" %>
		  </div>
		  <%= f.submit "Sign Up", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>